name: looping_diary
description: A Looping Diary project letting you see previous entries on the same day in different years

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^3.2.3+1
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dio: ^4.0.4
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  flutterfire_ui: ^0.3.4
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.3
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  logger: ^1.1.0
  mocktail: ^0.2.0
  permission_handler: ^9.0.1
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13

dev_dependencies:
  auto_route_generator: ^3.2.3
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator:
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - lib/res/images/
    - lib/res/translations/
