name: looping_diary
description: A Looping Diary project letting you see previous entries on the same day in different years

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  alchemist: ^0.3.3
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  awesome_dialog: ^2.2.1
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.2
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  firebase: ^9.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.0
  flutterfire_ui: ^0.4.1+2
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  http: ^0.13.4
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  lottie: ^1.3.0
  mocktail: ^0.3.0
  modal_bottom_sheet: ^2.0.1
  overlay_support: ^2.0.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  table_calendar: ^3.0.6

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator:
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - lib/res/images/
    - lib/res/lotties/
    - lib/res/icons/
    - lib/res/translations/
