// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9tTnQwVRhIIF91alfPHWsanr4wWjpyYM',
    appId: '1:941866307675:android:12d89ff5ff00f87aa42f7e',
    messagingSenderId: '941866307675',
    projectId: 'looping-diary',
    storageBucket: 'looping-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdeb8Ki88sx5-y_FizY0X_Rv1JzIU_X_Q',
    appId: '1:941866307675:ios:7017f5210684e2f4a42f7e',
    messagingSenderId: '941866307675',
    projectId: 'looping-diary',
    storageBucket: 'looping-diary.appspot.com',
    iosClientId: '941866307675-g789tiarcmb5mndd0ob0agjvemuc2qoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.loopingDiary',
  );
}
